version: '2'
services:
    uniteddairy-app:
        image: uniteddairy
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://uniteddairy-mysql:3306/uniteddairy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    uniteddairy-mysql:
        extends:
            file: mysql.yml
            service: uniteddairy-mysql
